version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /_frontend
    schedule:
      interval: daily
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      vue:
        patterns:
          - "vue"
          - "vue-router"
          - "vue-tsc"
          - "@vue/*"
          - "@vitejs/plugin-vue"
          - "@vuepic/*"
          - "@vueuse/*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "esbuild"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "typescript-eslint"
          - "@vue/eslint-config-typescript"
      typescript:
        patterns:
          - "typescript"
          - "@tsconfig/*"
          - "@vue/tsconfig"
          - "@types/*"
      walletconnect:
        patterns:
          - "@walletconnect/*"
      fortawesome:
        patterns:
          - "@fortawesome/*"
      cypress:
        patterns:
          - "cypress"
          - "@cypress/*"
          - "eslint-plugin-cypress"
      d3:
        patterns:
          - "d3"
          - "d3-*"
          - "@types/d3*"
          - "topojson-*"
          - "@types/topojson-*"