name: "ZXC: Release Helm Chart"

on:
  workflow_call:
    inputs:
      new-version:
        description: "New Release Version (ie. 0.30.0):"
        type: string
        required: true
      dry-run-enabled:
        description: "Perform Dry Run"
        type: boolean
        required: true

permissions:
  id-token: write
  packages: write
  contents: read

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8

jobs:
  chart:
    name: Chart
    runs-on: hiero-mirror-node-linux-medium
    defaults:
      run:
        working-directory: ./_frontend
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: "v3.12.3" #  helm version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set fallback version for debug
        id: set_fallback_version
        if: ${{ inputs.dry-run-enabled == true }}
        run: |
          VERSION="12.0.0"
          echo "FALLBACK VERSION=$VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set new version
        id: set_new_version
        run: |
          VERSION="${{ inputs.new-version }}"
          VERSION=${VERSION:-${{ steps.set_fallback_version.outputs.version }}}
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Update Helm Chart Version
        uses: mikefarah/yq@1187c954ec44c3a0e62c13ca7dc9dadc1ca80ae7 # v4.46.1
        env:
          relver: ${{ steps.set_new_version.outputs.version }}
        with:
          cmd: yq '.version = strenv(relver) | .appVersion = strenv(relver)' -i _frontend/chart/Chart.yaml

      - name: Show Helm Chart Manifest
        run: cat chart/Chart.yaml

      - name: Package Helm Chart
        run: helm package chart

      - name: Show Helm Chart Package
        run: ls -al *.tgz

      - name: Push Helm Chart
        if: ${{ inputs.dry-run-enabled != true }}
        run: helm push hiero-explorer-chart-${{ steps.set_new_version.outputs.version }}.tgz oci://ghcr.io/hiero-ledger/hiero-mirror-node-explorer
