name: "ZXC: Release Helm Chart"

on:
  workflow_call:
    inputs:
      new-version:
        description: "New Release Version (ie. 0.30.0):"
        type: string
        required: true
      dry-run-enabled:
        description: "Perform Dry Run"
        type: boolean
        required: true

permissions:
  id-token: write
  packages: write
  contents: read

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8

jobs:
  chart:
    name: Chart
    runs-on: hiero-mirror-node-linux-medium
    defaults:
      run:
        working-directory: ./_frontend
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        with:
          version: "v3.12.3" #  helm version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Update Helm Chart Version
        uses: mikefarah/yq@1b9b4ac5187171d2e5e3129be0cfa827c7f9d53d # v4.53.3
        env:
          relver: ${{ inputs.new-version }}
        with:
          cmd: yq '.version = strenv(relver) | .appVersion = strenv(relver)' -i _frontend/chart/Chart.yaml

      - name: Show Helm Chart Manifest
        run: cat chart/Chart.yaml

      - name: Package Helm Chart
        run: helm package chart

      - name: Show Helm Chart Package
        run: ls -al *.tgz

      - name: Push Helm Chart
        if: ${{ inputs.dry-run-enabled != true }}
        run: helm push hiero-explorer-chart-${{ inputs.new-version }}.tgz oci://ghcr.io/hiero-ledger/hiero-mirror-node-explorer
